<?php
/* @var $this QuBit_UniversalVariable_Block_Uv */
$_helper = $this->_getHelper();
if ($_helper->isEnabled()):
    /* @var $_catalogHelper QuBit_UniversalVariable_Helper_Catalog */
    $_catalogHelper = Mage::helper('universal_variable_main/catalog');
    $_product       = $_catalogHelper->getCurrentProductUvArray();
    $_listing       = $_catalogHelper->getListingUvArray();
?>
<!-- Universal Variable Start -->
<script type="text/javascript">
  window.universal_variable = window.universal_variable || {};
  window.universal_variable.version         = <?php echo json_encode($_helper->getVersion()); ?>;
  window.universal_variable.magento_version = <?php echo json_encode(Mage::getVersion()); ?>;
  window.universal_variable.page            = <?php echo json_encode($_helper->getPageType()); ?>;
  <?php if ($_product) : ?>
  window.universal_variable.product         = <?php echo json_encode($_product) ?>;
  <?php endif; ?>
  <?php if ($_listing): ?>
  window.universal_variable.listing         = <?php echo json_encode($_listing) ?>;
  <?php endif; ?>
  window.universal_variable.events          = <?php echo json_encode($this->getEvents()); ?>;
</script>
<!-- Universal Variable End -->
<?php echo $this->getChildHtml('universal_variable_session_data');?>
<?php
endif;
if ($_helper->opentagEnabled() && $_helper->getOpentagContainerId()) :
    $asyncTag = '';
    if ($_helper->isOpentagAsync()) {
        $asyncTag = 'async defer';
    }
?>
<!-- QuBit OpenTag Start -->
<script type="text/javascript" src='//d3c3cq33003psk.cloudfront.net/opentag-<?php echo $_helper->getOpentagContainerId();?>.js' <?php echo $asyncTag;?>></script>
<!-- QuBit OpenTag End -->
<?php endif;?>